# Generated by Django 5.0.3 on 2024-03-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=50)),
                ('stud_class', models.CharField(max_length=20)),
                ('stud_bday', models.DateField()),
            ],
        ),
    ]
