# Generated by Django 5.0.3 on 2024-03-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('std', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
